// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PPI.Api.Infrastructure.Persistence;

#nullable disable

namespace PPI.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PPI.Api.Domain.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Docente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsAuxiliar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PrimerLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ProgramaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("ProgramaId");

                    b.ToTable("docentes", (string)null);
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.EntradaInforme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnlaceEvidencias")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EnviadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("SinIniciar");

                    b.Property<string>("FirmaDigital")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GrupoAsignadoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuardadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InformeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObservacionAdmin")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoAsignadoId")
                        .IsUnique();

                    b.HasIndex("InformeId");

                    b.ToTable("entradas_informe", (string)null);
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.GrupoAsignado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Matriculados")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroGrupo")
                        .HasColumnType("integer");

                    b.Property<string>("Practica")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("ProgramaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramaId");

                    b.HasIndex("DocenteId", "Practica", "NumeroGrupo", "Semestre", "Anio")
                        .IsUnique();

                    b.ToTable("grupos_asignados", (string)null);
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Informe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<string>("CoordinadorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateOnly?>("FechaEntrega")
                        .HasColumnType("date");

                    b.Property<Guid>("ProgramaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramaId", "Semestre", "Anio")
                        .IsUnique();

                    b.ToTable("informes", (string)null);
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.InformeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("InformeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("InformeId");

                    b.ToTable("informe_auditorias", (string)null);
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Programa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("programas", (string)null);
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Docente", b =>
                {
                    b.HasOne("PPI.Api.Domain.Entities.Programa", "Programa")
                        .WithMany("Docentes")
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.EntradaInforme", b =>
                {
                    b.HasOne("PPI.Api.Domain.Entities.GrupoAsignado", "GrupoAsignado")
                        .WithOne("EntradaInforme")
                        .HasForeignKey("PPI.Api.Domain.Entities.EntradaInforme", "GrupoAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PPI.Api.Domain.Entities.Informe", "Informe")
                        .WithMany("Entradas")
                        .HasForeignKey("InformeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PPI.Api.Domain.Entities.Seccion2B", "Seccion2B", b1 =>
                        {
                            b1.Property<Guid>("EntradaInformeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("EnCasa")
                                .HasColumnType("integer");

                            b1.Property<int>("OngSocial")
                                .HasColumnType("integer");

                            b1.Property<int>("OtrosMunicipios")
                                .HasColumnType("integer");

                            b1.Property<int>("Privada")
                                .HasColumnType("integer");

                            b1.Property<int>("Publica")
                                .HasColumnType("integer");

                            b1.Property<int>("VinculacionLaboral")
                                .HasColumnType("integer");

                            b1.HasKey("EntradaInformeId");

                            b1.ToTable("entradas_informe");

                            b1.ToJson("Seccion2B");

                            b1.WithOwner()
                                .HasForeignKey("EntradaInformeId");
                        });

                    b.OwnsOne("PPI.Api.Domain.Entities.Seccion3", "Seccion3", b1 =>
                        {
                            b1.Property<Guid>("EntradaInformeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Finalizaron")
                                .HasColumnType("integer");

                            b1.Property<int>("Iniciaron")
                                .HasColumnType("integer");

                            b1.Property<int>("NoAprobaron")
                                .HasColumnType("integer");

                            b1.Property<int>("Pendientes")
                                .HasColumnType("integer");

                            b1.Property<int>("Retirados")
                                .HasColumnType("integer");

                            b1.HasKey("EntradaInformeId");

                            b1.ToTable("entradas_informe");

                            b1.ToJson("Seccion3");

                            b1.WithOwner()
                                .HasForeignKey("EntradaInformeId");
                        });

                    b.OwnsOne("PPI.Api.Domain.Entities.Seccion4A", "Seccion4A", b1 =>
                        {
                            b1.Property<Guid>("EntradaInformeId")
                                .HasColumnType("uuid");

                            b1.HasKey("EntradaInformeId");

                            b1.ToTable("entradas_informe");

                            b1.ToJson("Seccion4A");

                            b1.WithOwner()
                                .HasForeignKey("EntradaInformeId");

                            b1.OwnsOne("PPI.Api.Domain.Entities.ActividadItem", "ClasesEspejo", b2 =>
                                {
                                    b2.Property<Guid>("Seccion4AEntradaInformeId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("Aplica")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("Descripcion")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("Seccion4AEntradaInformeId");

                                    b2.ToTable("entradas_informe");

                                    b2.WithOwner()
                                        .HasForeignKey("Seccion4AEntradaInformeId");
                                });

                            b1.OwnsOne("PPI.Api.Domain.Entities.ActividadItem", "EventosAcademicos", b2 =>
                                {
                                    b2.Property<Guid>("Seccion4AEntradaInformeId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("Aplica")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("Descripcion")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("Seccion4AEntradaInformeId");

                                    b2.ToTable("entradas_informe");

                                    b2.WithOwner()
                                        .HasForeignKey("Seccion4AEntradaInformeId");
                                });

                            b1.OwnsOne("PPI.Api.Domain.Entities.ActividadItem", "SalidasCampo", b2 =>
                                {
                                    b2.Property<Guid>("Seccion4AEntradaInformeId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("Aplica")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("Descripcion")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("Seccion4AEntradaInformeId");

                                    b2.ToTable("entradas_informe");

                                    b2.WithOwner()
                                        .HasForeignKey("Seccion4AEntradaInformeId");
                                });

                            b1.Navigation("ClasesEspejo")
                                .IsRequired();

                            b1.Navigation("EventosAcademicos")
                                .IsRequired();

                            b1.Navigation("SalidasCampo")
                                .IsRequired();
                        });

                    b.OwnsOne("PPI.Api.Domain.Entities.Seccion4B", "Seccion4B", b1 =>
                        {
                            b1.Property<Guid>("EntradaInformeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Estrategias")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Otras")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Publicaciones")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EntradaInformeId");

                            b1.ToTable("entradas_informe");

                            b1.ToJson("Seccion4B");

                            b1.WithOwner()
                                .HasForeignKey("EntradaInformeId");
                        });

                    b.OwnsOne("PPI.Api.Domain.Entities.Seccion5A", "Seccion5A", b1 =>
                        {
                            b1.Property<Guid>("EntradaInformeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Lecciones")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Logros")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EntradaInformeId");

                            b1.ToTable("entradas_informe");

                            b1.ToJson("Seccion5A");

                            b1.WithOwner()
                                .HasForeignKey("EntradaInformeId");
                        });

                    b.OwnsOne("PPI.Api.Domain.Entities.Seccion5B", "Seccion5B", b1 =>
                        {
                            b1.Property<Guid>("EntradaInformeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Limitaciones")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Recomendaciones")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EntradaInformeId");

                            b1.ToTable("entradas_informe");

                            b1.ToJson("Seccion5B");

                            b1.WithOwner()
                                .HasForeignKey("EntradaInformeId");
                        });

                    b.Navigation("GrupoAsignado");

                    b.Navigation("Informe");

                    b.Navigation("Seccion2B");

                    b.Navigation("Seccion3");

                    b.Navigation("Seccion4A");

                    b.Navigation("Seccion4B");

                    b.Navigation("Seccion5A");

                    b.Navigation("Seccion5B");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.GrupoAsignado", b =>
                {
                    b.HasOne("PPI.Api.Domain.Entities.Docente", "Docente")
                        .WithMany("GruposAsignados")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PPI.Api.Domain.Entities.Programa", "Programa")
                        .WithMany("GruposAsignados")
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Informe", b =>
                {
                    b.HasOne("PPI.Api.Domain.Entities.Programa", "Programa")
                        .WithMany("Informes")
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.InformeAuditoria", b =>
                {
                    b.HasOne("PPI.Api.Domain.Entities.Admin", "Admin")
                        .WithMany("Auditorias")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PPI.Api.Domain.Entities.Informe", "Informe")
                        .WithMany("Auditorias")
                        .HasForeignKey("InformeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Informe");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Admin", b =>
                {
                    b.Navigation("Auditorias");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Docente", b =>
                {
                    b.Navigation("GruposAsignados");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.GrupoAsignado", b =>
                {
                    b.Navigation("EntradaInforme");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Informe", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Entradas");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Programa", b =>
                {
                    b.Navigation("Docentes");

                    b.Navigation("GruposAsignados");

                    b.Navigation("Informes");
                });
#pragma warning restore 612, 618
        }
    }
}
