// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PPI.Api.Infrastructure.Persistence;

#nullable disable

namespace PPI.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PPI.Api.Domain.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_admins");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_admins_correo");

                    b.ToTable("admins", (string)null);
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Docente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<bool>("EsAuxiliar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_auxiliar");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PrimerLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("primer_login");

                    b.Property<Guid>("ProgramaId")
                        .HasColumnType("uuid")
                        .HasColumnName("programa_id");

                    b.HasKey("Id")
                        .HasName("pk_docentes");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_docentes_correo");

                    b.HasIndex("ProgramaId")
                        .HasDatabaseName("ix_docentes_programa_id");

                    b.ToTable("docentes", (string)null);
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.EntradaInforme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("EnlaceEvidencias")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("enlace_evidencias");

                    b.Property<DateTime?>("EnviadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("SinIniciar")
                        .HasColumnName("estado");

                    b.Property<string>("FirmaDigital")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("firma_digital");

                    b.Property<Guid>("GrupoAsignadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_asignado_id");

                    b.Property<DateTime?>("GuardadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("guardado_en");

                    b.Property<Guid>("InformeId")
                        .HasColumnType("uuid")
                        .HasColumnName("informe_id");

                    b.Property<string>("ObservacionAdmin")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacion_admin");

                    b.HasKey("Id")
                        .HasName("pk_entradas_informe");

                    b.HasIndex("GrupoAsignadoId")
                        .IsUnique()
                        .HasDatabaseName("ix_entradas_informe_grupo_asignado_id");

                    b.HasIndex("InformeId")
                        .HasDatabaseName("ix_entradas_informe_informe_id");

                    b.ToTable("entradas_informe", (string)null);
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.GrupoAsignado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("docente_id");

                    b.Property<int>("Matriculados")
                        .HasColumnType("integer")
                        .HasColumnName("matriculados");

                    b.Property<int>("NumeroGrupo")
                        .HasColumnType("integer")
                        .HasColumnName("numero_grupo");

                    b.Property<string>("Practica")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("practica");

                    b.Property<Guid>("ProgramaId")
                        .HasColumnType("uuid")
                        .HasColumnName("programa_id");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("semestre");

                    b.HasKey("Id")
                        .HasName("pk_grupos_asignados");

                    b.HasIndex("ProgramaId")
                        .HasDatabaseName("ix_grupos_asignados_programa_id");

                    b.HasIndex("DocenteId", "Practica", "NumeroGrupo", "Semestre", "Anio")
                        .IsUnique()
                        .HasDatabaseName("ix_grupos_asignados_docente_id_practica_numero_grupo_semestre_");

                    b.ToTable("grupos_asignados", (string)null);
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Informe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<string>("CoordinadorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("coordinador_nombre");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega");

                    b.Property<Guid>("ProgramaId")
                        .HasColumnType("uuid")
                        .HasColumnName("programa_id");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("semestre");

                    b.HasKey("Id")
                        .HasName("pk_informes");

                    b.HasIndex("ProgramaId", "Semestre", "Anio")
                        .IsUnique()
                        .HasDatabaseName("ix_informes_programa_id_semestre_anio");

                    b.ToTable("informes", (string)null);
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.InformeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado_anterior");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado_nuevo");

                    b.Property<Guid>("InformeId")
                        .HasColumnType("uuid")
                        .HasColumnName("informe_id");

                    b.Property<string>("Observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacion");

                    b.HasKey("Id")
                        .HasName("pk_informe_auditorias");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("ix_informe_auditorias_admin_id");

                    b.HasIndex("InformeId")
                        .HasDatabaseName("ix_informe_auditorias_informe_id");

                    b.ToTable("informe_auditorias", (string)null);
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Programa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_programas");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_programas_codigo");

                    b.ToTable("programas", (string)null);
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Docente", b =>
                {
                    b.HasOne("PPI.Api.Domain.Entities.Programa", "Programa")
                        .WithMany("Docentes")
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_docentes_programas_programa_id");

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.EntradaInforme", b =>
                {
                    b.HasOne("PPI.Api.Domain.Entities.GrupoAsignado", "GrupoAsignado")
                        .WithOne("EntradaInforme")
                        .HasForeignKey("PPI.Api.Domain.Entities.EntradaInforme", "GrupoAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entradas_informe_grupos_asignados_grupo_asignado_id");

                    b.HasOne("PPI.Api.Domain.Entities.Informe", "Informe")
                        .WithMany("Entradas")
                        .HasForeignKey("InformeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entradas_informe_informes_informe_id");

                    b.OwnsOne("PPI.Api.Domain.Entities.Seccion2B", "Seccion2B", b1 =>
                        {
                            b1.Property<Guid>("EntradaInformeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("EnCasa")
                                .HasColumnType("integer");

                            b1.Property<int>("OngSocial")
                                .HasColumnType("integer");

                            b1.Property<int>("OtrosMunicipios")
                                .HasColumnType("integer");

                            b1.Property<int>("Privada")
                                .HasColumnType("integer");

                            b1.Property<int>("Publica")
                                .HasColumnType("integer");

                            b1.Property<int>("VinculacionLaboral")
                                .HasColumnType("integer");

                            b1.HasKey("EntradaInformeId");

                            b1.ToTable("entradas_informe");

                            b1.ToJson("seccion2b");

                            b1.WithOwner()
                                .HasForeignKey("EntradaInformeId")
                                .HasConstraintName("fk_entradas_informe_entradas_informe_id");
                        });

                    b.OwnsOne("PPI.Api.Domain.Entities.Seccion3", "Seccion3", b1 =>
                        {
                            b1.Property<Guid>("EntradaInformeId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Finalizaron")
                                .HasColumnType("integer");

                            b1.Property<int>("Iniciaron")
                                .HasColumnType("integer");

                            b1.Property<int>("NoAprobaron")
                                .HasColumnType("integer");

                            b1.Property<int>("Pendientes")
                                .HasColumnType("integer");

                            b1.Property<int>("Retirados")
                                .HasColumnType("integer");

                            b1.HasKey("EntradaInformeId");

                            b1.ToTable("entradas_informe");

                            b1.ToJson("seccion3");

                            b1.WithOwner()
                                .HasForeignKey("EntradaInformeId")
                                .HasConstraintName("fk_entradas_informe_entradas_informe_id");
                        });

                    b.OwnsOne("PPI.Api.Domain.Entities.Seccion4A", "Seccion4A", b1 =>
                        {
                            b1.Property<Guid>("EntradaInformeId")
                                .HasColumnType("uuid");

                            b1.HasKey("EntradaInformeId");

                            b1.ToTable("entradas_informe");

                            b1.ToJson("seccion4a");

                            b1.WithOwner()
                                .HasForeignKey("EntradaInformeId")
                                .HasConstraintName("fk_entradas_informe_entradas_informe_id");

                            b1.OwnsOne("PPI.Api.Domain.Entities.ActividadItem", "ClasesEspejo", b2 =>
                                {
                                    b2.Property<Guid>("Seccion4AEntradaInformeId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("Aplica")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("Descripcion")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("Seccion4AEntradaInformeId");

                                    b2.ToTable("entradas_informe");

                                    b2.ToJson("seccion4a");

                                    b2.WithOwner()
                                        .HasForeignKey("Seccion4AEntradaInformeId")
                                        .HasConstraintName("fk_entradas_informe_entradas_informe_seccion4a_entrada_informe_id");
                                });

                            b1.OwnsOne("PPI.Api.Domain.Entities.ActividadItem", "EventosAcademicos", b2 =>
                                {
                                    b2.Property<Guid>("Seccion4AEntradaInformeId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("Aplica")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("Descripcion")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("Seccion4AEntradaInformeId");

                                    b2.ToTable("entradas_informe");

                                    b2.ToJson("seccion4a");

                                    b2.WithOwner()
                                        .HasForeignKey("Seccion4AEntradaInformeId")
                                        .HasConstraintName("fk_entradas_informe_entradas_informe_seccion4a_entrada_informe_id");
                                });

                            b1.OwnsOne("PPI.Api.Domain.Entities.ActividadItem", "SalidasCampo", b2 =>
                                {
                                    b2.Property<Guid>("Seccion4AEntradaInformeId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("Aplica")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("Descripcion")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("Seccion4AEntradaInformeId");

                                    b2.ToTable("entradas_informe");

                                    b2.ToJson("seccion4a");

                                    b2.WithOwner()
                                        .HasForeignKey("Seccion4AEntradaInformeId")
                                        .HasConstraintName("fk_entradas_informe_entradas_informe_seccion4a_entrada_informe_id");
                                });

                            b1.Navigation("ClasesEspejo")
                                .IsRequired();

                            b1.Navigation("EventosAcademicos")
                                .IsRequired();

                            b1.Navigation("SalidasCampo")
                                .IsRequired();
                        });

                    b.OwnsOne("PPI.Api.Domain.Entities.Seccion4B", "Seccion4B", b1 =>
                        {
                            b1.Property<Guid>("EntradaInformeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Estrategias")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Otras")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Publicaciones")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EntradaInformeId");

                            b1.ToTable("entradas_informe");

                            b1.ToJson("seccion4b");

                            b1.WithOwner()
                                .HasForeignKey("EntradaInformeId")
                                .HasConstraintName("fk_entradas_informe_entradas_informe_id");
                        });

                    b.OwnsOne("PPI.Api.Domain.Entities.Seccion5A", "Seccion5A", b1 =>
                        {
                            b1.Property<Guid>("EntradaInformeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Lecciones")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Logros")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EntradaInformeId");

                            b1.ToTable("entradas_informe");

                            b1.ToJson("seccion5a");

                            b1.WithOwner()
                                .HasForeignKey("EntradaInformeId")
                                .HasConstraintName("fk_entradas_informe_entradas_informe_id");
                        });

                    b.OwnsOne("PPI.Api.Domain.Entities.Seccion5B", "Seccion5B", b1 =>
                        {
                            b1.Property<Guid>("EntradaInformeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Limitaciones")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Recomendaciones")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EntradaInformeId");

                            b1.ToTable("entradas_informe");

                            b1.ToJson("seccion5b");

                            b1.WithOwner()
                                .HasForeignKey("EntradaInformeId")
                                .HasConstraintName("fk_entradas_informe_entradas_informe_id");
                        });

                    b.Navigation("GrupoAsignado");

                    b.Navigation("Informe");

                    b.Navigation("Seccion2B");

                    b.Navigation("Seccion3");

                    b.Navigation("Seccion4A");

                    b.Navigation("Seccion4B");

                    b.Navigation("Seccion5A");

                    b.Navigation("Seccion5B");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.GrupoAsignado", b =>
                {
                    b.HasOne("PPI.Api.Domain.Entities.Docente", "Docente")
                        .WithMany("GruposAsignados")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grupos_asignados_docentes_docente_id");

                    b.HasOne("PPI.Api.Domain.Entities.Programa", "Programa")
                        .WithMany("GruposAsignados")
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grupos_asignados_programas_programa_id");

                    b.Navigation("Docente");

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Informe", b =>
                {
                    b.HasOne("PPI.Api.Domain.Entities.Programa", "Programa")
                        .WithMany("Informes")
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_informes_programas_programa_id");

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.InformeAuditoria", b =>
                {
                    b.HasOne("PPI.Api.Domain.Entities.Admin", "Admin")
                        .WithMany("Auditorias")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_informe_auditorias_admins_admin_id");

                    b.HasOne("PPI.Api.Domain.Entities.Informe", "Informe")
                        .WithMany("Auditorias")
                        .HasForeignKey("InformeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_informe_auditorias_informes_informe_id");

                    b.Navigation("Admin");

                    b.Navigation("Informe");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Admin", b =>
                {
                    b.Navigation("Auditorias");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Docente", b =>
                {
                    b.Navigation("GruposAsignados");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.GrupoAsignado", b =>
                {
                    b.Navigation("EntradaInforme");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Informe", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Entradas");
                });

            modelBuilder.Entity("PPI.Api.Domain.Entities.Programa", b =>
                {
                    b.Navigation("Docentes");

                    b.Navigation("GruposAsignados");

                    b.Navigation("Informes");
                });
#pragma warning restore 612, 618
        }
    }
}
