/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // M3 tokens (from Stitch design system)
        primary:                    '#002f5a',
        'primary-container':        '#004581',
        'on-primary':               '#ffffff',
        'on-primary-container':     '#86b4f7',
        'primary-fixed':            '#d4e3ff',
        'primary-fixed-dim':        '#a5c8ff',
        'on-primary-fixed':         '#001c3a',
        'on-primary-fixed-variant': '#054783',
        secondary:                  '#3d608a',
        'secondary-container':      '#accffe',
        'on-secondary':             '#ffffff',
        'on-secondary-container':   '#355881',
        'secondary-fixed':          '#d2e4ff',
        'secondary-fixed-dim':      '#a6c9f8',
        'on-secondary-fixed':       '#001c37',
        'on-secondary-fixed-variant': '#244871',
        tertiary:                   '#2b2f31',
        'tertiary-container':       '#414548',
        'on-tertiary':              '#ffffff',
        'on-tertiary-container':    '#afb2b5',
        'tertiary-fixed':           '#e0e3e6',
        'tertiary-fixed-dim':       '#c4c7ca',
        'on-tertiary-fixed':        '#181c1e',
        'on-tertiary-fixed-variant':'#43474a',
        error:                      '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',
        surface:                    '#f6faff',
        'surface-dim':              '#d2dbe4',
        'surface-bright':           '#f6faff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#ecf5fe',
        'surface-container':        '#e6eff8',
        'surface-container-high':   '#e0e9f2',
        'surface-container-highest':'#dbe4ed',
        'surface-tint':             '#2c609d',
        'surface-variant':          '#dbe4ed',
        'on-surface':               '#141d23',
        'on-surface-variant':       '#424750',
        'inverse-surface':          '#293138',
        'inverse-on-surface':       '#e9f2fb',
        'inverse-primary':          '#a5c8ff',
        outline:                    '#727781',
        'outline-variant':          '#c2c6d1',
        background:                 '#f6faff',
        'on-background':            '#141d23',
        // Semantic aliases (used by Login, Badge, etc.)
        accent:   '#c25d41',
        success: { DEFAULT: '#16a34a', bg: '#f0fdf4' },
        danger:  { DEFAULT: '#dc2626', bg: '#fef2f2' },
        warning: { DEFAULT: '#d97706', bg: '#fffbeb' },
        text: {
          main:      '#0f172a',
          secondary: '#475569',
          muted:     '#94a3b8',
        },
        card: { border: 'rgba(194,198,209,0.4)' },
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-lg':        ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg-mobile': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'headline-md':        ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm':            ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps':         ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em' }],
      },
      spacing: {
        'sidebar-width':      '260px',
        'container-padding':  '2rem',
        'gutter-md':          '1.5rem',
        'stack-md':           '1.5rem',
        'stack-sm':           '0.75rem',
      },
      boxShadow: {
        card: '0 2px 16px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
}
